/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author kacor
 */
public class PaginaPrincipalView extends javax.swing.JFrame {
    Color naranjaOscuro = new Color(242,68,5);
    Color naranja = new Color(242,98,15);
    /**
     * Creates new form PaginaPrincipalView2
     */
    public PaginaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        GrupoDePaneles = new javax.swing.JTabbedPane();
        paginaPrincipalPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        panelGananciasTotales = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        lblNumGanancias = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblNombreGimnasio = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreoElectronico = new javax.swing.JLabel();
        panelMembresias = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        lblNumMembresias = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        panelSocios = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        lblNumSocios = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        panelMaquinas = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        lblNumMaquinas = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        panelEntrenadores = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        lblNumEntrenadores = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        panelClasesActividades = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        lblNumClases = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        paginaSociosPanel = new javax.swing.JPanel();
        btnRegistrarNuevoSocio = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        btnVerSocios = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAdministrarSocios = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        paginaMembresiasPanel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        btnRegistrarMembresia = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btnAgregarTipoMembresia = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btnListaMembresias = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        paginaClasesPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        paginaActividadesPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        paginaEspaciosPanel = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        paginaMaquinasPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        paginaInformesPanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        menuLateral = new javax.swing.JPanel();
        jpPaginaPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpCerrarSesion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpSocios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpPagos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpClases = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpActividades = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jpEspacios = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jpMaquinas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jpInformes = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagina Principal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Bienvenido Admin");
        header.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoBarraBlanco.png"))); // NOI18N
        header.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gimnasio");
        header.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraTitulo.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.setPreferredSize(new java.awt.Dimension(1280, 100));
        header.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        GrupoDePaneles.setBackground(new java.awt.Color(255, 255, 255));

        paginaPrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));
        paginaPrincipalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        paginaPrincipalPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 440, 10));

        panelGananciasTotales.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(0, 204, 51)));
        panelGananciasTotales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel37.setText("Totales");
        jLabel37.setToolTipText("");
        jLabel37.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelGananciasTotales.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        lblNumGanancias.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        lblNumGanancias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumGanancias.setText("0");
        panelGananciasTotales.add(lblNumGanancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, 50));

        jLabel41.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel41.setText("Ganancias");
        jLabel41.setToolTipText("");
        jLabel41.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelGananciasTotales.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        paginaPrincipalPanel.add(panelGananciasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 200, 80));

        lblNombreGimnasio.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        lblNombreGimnasio.setText("Nombre del Gimnasio");
        paginaPrincipalPanel.add(lblNombreGimnasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lblTelefono.setText("Telefono");
        paginaPrincipalPanel.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

        lblCorreoElectronico.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lblCorreoElectronico.setText("Correo electronico");
        paginaPrincipalPanel.add(lblCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, -1));

        panelMembresias.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(102, 255, 0)));
        panelMembresias.setForeground(new java.awt.Color(153, 255, 153));
        panelMembresias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel39.setText("Membresias");
        panelMembresias.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        lblNumMembresias.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        lblNumMembresias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumMembresias.setText("0");
        panelMembresias.add(lblNumMembresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 60, 50));

        jLabel51.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel51.setText("Registrados");
        jLabel51.setToolTipText("");
        jLabel51.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelMembresias.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 30));

        paginaPrincipalPanel.add(panelMembresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 200, 80));

        panelSocios.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        panelSocios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel42.setText("Registrados");
        jLabel42.setToolTipText("");
        jLabel42.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelSocios.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 30));

        lblNumSocios.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        lblNumSocios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumSocios.setText("0");
        panelSocios.add(lblNumSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 60, 50));

        jLabel44.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel44.setText("Socios");
        jLabel44.setToolTipText("");
        jLabel44.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelSocios.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        paginaPrincipalPanel.add(panelSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 200, 80));

        panelMaquinas.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(255, 51, 0)));
        panelMaquinas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel45.setText("Activas");
        jLabel45.setToolTipText("");
        jLabel45.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelMaquinas.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        lblNumMaquinas.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        lblNumMaquinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumMaquinas.setText("0");
        panelMaquinas.add(lblNumMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, 50));

        jLabel47.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel47.setText("Maquinas");
        jLabel47.setToolTipText("");
        jLabel47.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelMaquinas.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        paginaPrincipalPanel.add(panelMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 200, 80));

        panelEntrenadores.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(255, 51, 0)));
        panelEntrenadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel48.setText("Activos");
        jLabel48.setToolTipText("");
        jLabel48.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelEntrenadores.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        lblNumEntrenadores.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        lblNumEntrenadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumEntrenadores.setText("0");
        panelEntrenadores.add(lblNumEntrenadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 60, 50));

        jLabel50.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel50.setText("Entrenadores");
        jLabel50.setToolTipText("");
        jLabel50.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelEntrenadores.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        paginaPrincipalPanel.add(panelEntrenadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 200, 80));

        panelClasesActividades.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(255, 51, 0)));
        panelClasesActividades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel52.setText("Actividades");
        jLabel52.setToolTipText("");
        jLabel52.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelClasesActividades.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        lblNumClases.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        lblNumClases.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumClases.setText("0");
        panelClasesActividades.add(lblNumClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, 50));

        jLabel54.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel54.setText("Clases y");
        jLabel54.setToolTipText("");
        jLabel54.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelClasesActividades.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        paginaPrincipalPanel.add(panelClasesActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 200, 80));

        lblDireccion.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lblDireccion.setText("Direccion");
        paginaPrincipalPanel.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 390, -1));

        GrupoDePaneles.addTab("tab1", paginaPrincipalPanel);

        paginaSociosPanel.setBackground(new java.awt.Color(255, 255, 255));
        paginaSociosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarNuevoSocio.setBackground(new java.awt.Color(255, 153, 102));
        btnRegistrarNuevoSocio.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnRegistrarNuevoSocio.setText("Registrar un nuevo socio");
        btnRegistrarNuevoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNuevoSocioActionPerformed(evt);
            }
        });
        paginaSociosPanel.add(btnRegistrarNuevoSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 1.jpg"))); // NOI18N
        paginaSociosPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        btnVerSocios.setBackground(new java.awt.Color(255, 153, 102));
        btnVerSocios.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnVerSocios.setText("Ver socios existentes");
        btnVerSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSociosActionPerformed(evt);
            }
        });
        paginaSociosPanel.add(btnVerSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 200, 40));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 2 (1).png"))); // NOI18N
        paginaSociosPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1366_2000.jpeg"))); // NOI18N
        paginaSociosPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 260, 300));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 2 (1).png"))); // NOI18N
        paginaSociosPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 270, -1));

        jLabel25.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        jLabel25.setText("Socios");
        paginaSociosPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        paginaSociosPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 10));

        btnAdministrarSocios.setBackground(new java.awt.Color(255, 153, 102));
        btnAdministrarSocios.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnAdministrarSocios.setText("Administrar información");
        btnAdministrarSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarSociosActionPerformed(evt);
            }
        });
        paginaSociosPanel.add(btnAdministrarSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 200, 40));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/slide-multifuerza-002.jpg"))); // NOI18N
        paginaSociosPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 260, 300));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 2 (1).png"))); // NOI18N
        paginaSociosPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 270, -1));

        GrupoDePaneles.addTab("tab2", paginaSociosPanel);

        paginaMembresiasPanel.setBackground(new java.awt.Color(255, 255, 255));
        paginaMembresiasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 1.jpg"))); // NOI18N
        paginaMembresiasPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        btnRegistrarMembresia.setBackground(new java.awt.Color(255, 153, 102));
        btnRegistrarMembresia.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnRegistrarMembresia.setText("Registrar una membresia");
        btnRegistrarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMembresiaActionPerformed(evt);
            }
        });
        paginaMembresiasPanel.add(btnRegistrarMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, 40));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 2 (1).png"))); // NOI18N
        paginaMembresiasPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 270, -1));
        paginaMembresiasPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 10));

        jLabel40.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        jLabel40.setText("Membresias");
        paginaMembresiasPanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/slide-multifuerza-002.jpg"))); // NOI18N
        paginaMembresiasPanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 250, -1));

        btnAgregarTipoMembresia.setBackground(new java.awt.Color(255, 153, 102));
        btnAgregarTipoMembresia.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnAgregarTipoMembresia.setText("Agregar un tipo de membresia");
        btnAgregarTipoMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoMembresiaActionPerformed(evt);
            }
        });
        paginaMembresiasPanel.add(btnAgregarTipoMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, 40));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1366_2000.jpeg"))); // NOI18N
        paginaMembresiasPanel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 250, 300));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 2 (1).png"))); // NOI18N
        paginaMembresiasPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 270, -1));

        btnListaMembresias.setBackground(new java.awt.Color(255, 153, 102));
        btnListaMembresias.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnListaMembresias.setText("Ver lista de membresias");
        btnListaMembresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaMembresiasActionPerformed(evt);
            }
        });
        paginaMembresiasPanel.add(btnListaMembresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, 40));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 2 (1).png"))); // NOI18N
        paginaMembresiasPanel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 270, -1));

        GrupoDePaneles.addTab("tab3", paginaMembresiasPanel);

        paginaClasesPanel.setBackground(new java.awt.Color(255, 255, 255));
        paginaClasesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("Clases");
        paginaClasesPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        GrupoDePaneles.addTab("tab4", paginaClasesPanel);

        paginaActividadesPanel.setBackground(new java.awt.Color(255, 255, 255));
        paginaActividadesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("Actividades");
        paginaActividadesPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        GrupoDePaneles.addTab("tab5", paginaActividadesPanel);

        paginaEspaciosPanel.setBackground(new java.awt.Color(255, 255, 255));
        paginaEspaciosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Espacios");
        paginaEspaciosPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        GrupoDePaneles.addTab("tab6", paginaEspaciosPanel);

        paginaMaquinasPanel.setBackground(new java.awt.Color(255, 255, 255));
        paginaMaquinasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("Maquinas");
        paginaMaquinasPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        GrupoDePaneles.addTab("tab7", paginaMaquinasPanel);

        paginaInformesPanel.setBackground(new java.awt.Color(255, 255, 255));
        paginaInformesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setText("Infromes y analisis");
        paginaInformesPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        GrupoDePaneles.addTab("tab8", paginaInformesPanel);

        background.add(GrupoDePaneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 1010, 650));

        menuLateral.setBackground(new java.awt.Color(242, 98, 15));
        menuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpPaginaPrincipal.setBackground(new java.awt.Color(242, 98, 15));
        jpPaginaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPaginaPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpPaginaPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpPaginaPrincipalMouseExited(evt);
            }
        });
        jpPaginaPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel1.setText("Pagina Principal");
        jpPaginaPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoHomeMancuerna.png"))); // NOI18N
        jpPaginaPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpPaginaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 50));

        jpCerrarSesion.setBackground(new java.awt.Color(242, 98, 15));
        jpCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMouseExited(evt);
            }
        });
        jpCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel3.setText("Cerrar Sesion");
        jpCerrarSesion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoCerrarSesion.png"))); // NOI18N
        jpCerrarSesion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 270, 50));

        jpSocios.setBackground(new java.awt.Color(242, 98, 15));
        jpSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpSociosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpSociosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpSociosMouseExited(evt);
            }
        });
        jpSocios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel5.setText("Socios");
        jpSocios.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoSocioNegro.png"))); // NOI18N
        jpSocios.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 50));

        jpPagos.setBackground(new java.awt.Color(242, 98, 15));
        jpPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpPagosMouseExited(evt);
            }
        });
        jpPagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel7.setText("Membresias");
        jpPagos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoMembresiaNegro.png"))); // NOI18N
        jpPagos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, 50));

        jpClases.setBackground(new java.awt.Color(242, 98, 15));
        jpClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpClasesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpClasesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpClasesMouseExited(evt);
            }
        });
        jpClases.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel9.setText("Clases");
        jpClases.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoHombreMancuerna.png"))); // NOI18N
        jpClases.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, 50));

        jpActividades.setBackground(new java.awt.Color(242, 98, 15));
        jpActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpActividadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpActividadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpActividadesMouseExited(evt);
            }
        });
        jpActividades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel11.setText("Actividades");
        jpActividades.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoParejaNegro.png"))); // NOI18N
        jpActividades.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 270, 50));

        jpEspacios.setBackground(new java.awt.Color(242, 98, 15));
        jpEspacios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEspaciosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpEspaciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpEspaciosMouseExited(evt);
            }
        });
        jpEspacios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel13.setText("Espacios");
        jpEspacios.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoEspacios.png"))); // NOI18N
        jpEspacios.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 270, 50));

        jpMaquinas.setBackground(new java.awt.Color(242, 98, 15));
        jpMaquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMaquinasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpMaquinasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpMaquinasMouseExited(evt);
            }
        });
        jpMaquinas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel15.setText("Maquinas");
        jpMaquinas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoMaquinas.png"))); // NOI18N
        jpMaquinas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 270, 50));

        jpInformes.setBackground(new java.awt.Color(242, 98, 15));
        jpInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpInformesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpInformesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpInformesMouseExited(evt);
            }
        });
        jpInformes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel19.setText("Informes y analisis");
        jpInformes.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconoInformes.png"))); // NOI18N
        jpInformes.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuLateral.add(jpInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 270, 50));

        background.add(menuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 680));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpPaginaPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPaginaPrincipalMouseEntered
        // TODO add your handling code here:
        jpPaginaPrincipal.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpPaginaPrincipalMouseEntered

    private void jpPaginaPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPaginaPrincipalMouseExited
        // TODO add your handling code here:
        jpPaginaPrincipal.setBackground(naranja);
    }//GEN-LAST:event_jpPaginaPrincipalMouseExited

    private void jpSociosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSociosMouseEntered
        // TODO add your handling code here:
        jpSocios.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpSociosMouseEntered

    private void jpSociosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSociosMouseExited
        // TODO add your handling code here:
        jpSocios.setBackground(naranja);
    }//GEN-LAST:event_jpSociosMouseExited

    private void jpPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPagosMouseEntered
        // TODO add your handling code here:
        jpPagos.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpPagosMouseEntered

    private void jpPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPagosMouseExited
        // TODO add your handling code here:
        jpPagos.setBackground(naranja);
    }//GEN-LAST:event_jpPagosMouseExited

    private void jpClasesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpClasesMouseEntered
        // TODO add your handling code here:
        jpClases.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpClasesMouseEntered

    private void jpClasesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpClasesMouseExited
        // TODO add your handling code here:
        jpClases.setBackground(naranja);
    }//GEN-LAST:event_jpClasesMouseExited

    private void jpActividadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActividadesMouseEntered
        // TODO add your handling code here:
        jpActividades.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpActividadesMouseEntered

    private void jpActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActividadesMouseExited
        // TODO add your handling code here:
        jpActividades.setBackground(naranja);
    }//GEN-LAST:event_jpActividadesMouseExited

    private void jpEspaciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEspaciosMouseEntered
        // TODO add your handling code here:
        jpEspacios.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpEspaciosMouseEntered

    private void jpEspaciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEspaciosMouseExited
        // TODO add your handling code here:
        jpEspacios.setBackground(naranja);
    }//GEN-LAST:event_jpEspaciosMouseExited

    private void jpMaquinasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMaquinasMouseEntered
        // TODO add your handling code here:
        jpMaquinas.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpMaquinasMouseEntered

    private void jpMaquinasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMaquinasMouseExited
        // TODO add your handling code here:
        jpMaquinas.setBackground(naranja);
    }//GEN-LAST:event_jpMaquinasMouseExited

    private void jpInformesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInformesMouseEntered
        // TODO add your handling code here:
        jpInformes.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpInformesMouseEntered

    private void jpInformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInformesMouseExited
        // TODO add your handling code here:
        jpInformes.setBackground(naranja);
    }//GEN-LAST:event_jpInformesMouseExited

    private void jpCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMouseEntered
        // TODO add your handling code here:
        jpCerrarSesion.setBackground(naranjaOscuro);
    }//GEN-LAST:event_jpCerrarSesionMouseEntered

    private void jpCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMouseExited
        // TODO add your handling code here:
        jpCerrarSesion.setBackground(naranja);
    }//GEN-LAST:event_jpCerrarSesionMouseExited

    private void jpCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jpCerrarSesionMouseClicked

    private void jpPaginaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPaginaPrincipalMouseClicked
        // TODO add your handling code here:
        GrupoDePaneles.setSelectedIndex(0);
    }//GEN-LAST:event_jpPaginaPrincipalMouseClicked

    private void jpSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSociosMouseClicked
        // TODO add your handling code here:
        GrupoDePaneles.setSelectedIndex(1);
    }//GEN-LAST:event_jpSociosMouseClicked

    private void jpPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPagosMouseClicked
        // TODO add your handling code here:
        GrupoDePaneles.setSelectedIndex(2);
    }//GEN-LAST:event_jpPagosMouseClicked

    private void jpClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpClasesMouseClicked
        // TODO add your handling code here:
        GrupoDePaneles.setSelectedIndex(3);
    }//GEN-LAST:event_jpClasesMouseClicked

    private void jpActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActividadesMouseClicked
        // TODO add your handling code here:
        GrupoDePaneles.setSelectedIndex(4);
    }//GEN-LAST:event_jpActividadesMouseClicked

    private void jpEspaciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEspaciosMouseClicked
        // TODO add your handling code here:
        GrupoDePaneles.setSelectedIndex(5);
    }//GEN-LAST:event_jpEspaciosMouseClicked

    private void jpMaquinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMaquinasMouseClicked
        // TODO add your handling code here:
        GrupoDePaneles.setSelectedIndex(6);
    }//GEN-LAST:event_jpMaquinasMouseClicked

    private void jpInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInformesMouseClicked
        // TODO add your handling code here:
        GrupoDePaneles.setSelectedIndex(7);
    }//GEN-LAST:event_jpInformesMouseClicked

    private void btnRegistrarNuevoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarNuevoSocioActionPerformed

    private void btnVerSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerSociosActionPerformed

    private void btnRegistrarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarMembresiaActionPerformed

    private void btnAdministrarSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarSociosActionPerformed

    private void btnAgregarTipoMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarTipoMembresiaActionPerformed

    private void btnListaMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaMembresiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaMembresiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane GrupoDePaneles;
    private javax.swing.JPanel background;
    public javax.swing.JButton btnAdministrarSocios;
    public javax.swing.JButton btnAgregarTipoMembresia;
    public javax.swing.JButton btnListaMembresias;
    public javax.swing.JButton btnRegistrarMembresia;
    public javax.swing.JButton btnRegistrarNuevoSocio;
    public javax.swing.JButton btnVerSocios;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jpActividades;
    private javax.swing.JPanel jpCerrarSesion;
    private javax.swing.JPanel jpClases;
    private javax.swing.JPanel jpEspacios;
    private javax.swing.JPanel jpInformes;
    private javax.swing.JPanel jpMaquinas;
    private javax.swing.JPanel jpPaginaPrincipal;
    private javax.swing.JPanel jpPagos;
    private javax.swing.JPanel jpSocios;
    public javax.swing.JLabel lblCorreoElectronico;
    public javax.swing.JLabel lblDireccion;
    public javax.swing.JLabel lblNombreGimnasio;
    private javax.swing.JLabel lblNumClases;
    private javax.swing.JLabel lblNumEntrenadores;
    private javax.swing.JLabel lblNumGanancias;
    private javax.swing.JLabel lblNumMaquinas;
    public javax.swing.JLabel lblNumMembresias;
    public javax.swing.JLabel lblNumSocios;
    public javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel paginaActividadesPanel;
    private javax.swing.JPanel paginaClasesPanel;
    private javax.swing.JPanel paginaEspaciosPanel;
    private javax.swing.JPanel paginaInformesPanel;
    private javax.swing.JPanel paginaMaquinasPanel;
    private javax.swing.JPanel paginaMembresiasPanel;
    private javax.swing.JPanel paginaPrincipalPanel;
    private javax.swing.JPanel paginaSociosPanel;
    private javax.swing.JPanel panelClasesActividades;
    private javax.swing.JPanel panelEntrenadores;
    private javax.swing.JPanel panelGananciasTotales;
    private javax.swing.JPanel panelMaquinas;
    private javax.swing.JPanel panelMembresias;
    private javax.swing.JPanel panelSocios;
    // End of variables declaration//GEN-END:variables
}
