package view;

/**
 *
 * @author kacor
 */
public class RegistroMembresiaView extends javax.swing.JFrame {

    /**
     * Creates new form RegistroMembresiaView
     */
    public RegistroMembresiaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cmbCriterioBusqueda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnCobrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbTipoMembresia = new javax.swing.JComboBox<>();
        lblDescripcionMembresia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMembresia = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtCedula1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registro de Membresia");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraTitulo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        txtBusqueda.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        bg.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 160, 30));

        cmbCriterioBusqueda.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        cmbCriterioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Cedula", "Apellido" }));
        bg.add(cmbCriterioBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, 30));

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setText("Seleccionar socio por:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        btnCobrar.setBackground(new java.awt.Color(242, 98, 15));
        btnCobrar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setText("Cobrar");
        btnCobrar.setBorder(null);
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        bg.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 120, 30));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setText("Cedula:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtTotalPagar.setFont(new java.awt.Font("IBM Plex Mono", 0, 14)); // NOI18N
        txtTotalPagar.setEnabled(false);
        bg.add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 130, 27));

        txtNombre.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        txtNombre.setEnabled(false);
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 150, 27));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setText("Apellido:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtApellido.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        txtApellido.setEnabled(false);
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 150, 27));

        txtEmail.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        txtEmail.setEnabled(false);
        bg.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 150, 27));

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setText("Total a pagar:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 110, -1));

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setText("Telefono:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        txtTelefono.setEnabled(false);
        bg.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 150, 27));

        txtDireccion.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        txtDireccion.setEnabled(false);
        bg.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 150, 27));

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel9.setText("Direccion:");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 292, 770, 10));

        cmbTipoMembresia.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        cmbTipoMembresia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cmbTipoMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoMembresiaActionPerformed(evt);
            }
        });
        bg.add(cmbTipoMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 220, 30));

        lblDescripcionMembresia.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        lblDescripcionMembresia.setText("Descripcion de la membresia");
        bg.add(lblDescripcionMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 220, -1));

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel11.setText("Elegir tipo de membresia:");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 220, -1));

        jtMembresia.setFont(new java.awt.Font("IBM Plex Mono", 0, 12)); // NOI18N
        jtMembresia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMembresia.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jtMembresia);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 470, 110));

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel12.setText("Email:");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        txtCedula1.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        txtCedula1.setEnabled(false);
        bg.add(txtCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 150, 27));

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel13.setText("Subtotal:");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 70, -1));

        txtSubtotal.setFont(new java.awt.Font("IBM Plex Mono", 0, 14)); // NOI18N
        txtSubtotal.setEnabled(false);
        bg.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 130, 27));

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel14.setText("IVA:");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 30, -1));

        txtIVA.setFont(new java.awt.Font("IBM Plex Mono", 0, 14)); // NOI18N
        txtIVA.setEnabled(false);
        bg.add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 130, 27));

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel15.setText("Efectivo:");
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 70, -1));

        txtEfectivo.setFont(new java.awt.Font("IBM Plex Mono", 0, 14)); // NOI18N
        bg.add(txtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 130, 27));

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel16.setText("Cambio:");
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 70, -1));

        txtCambio.setFont(new java.awt.Font("IBM Plex Mono", 0, 14)); // NOI18N
        txtCambio.setEnabled(false);
        bg.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 130, 27));

        btnBuscar.setBackground(new java.awt.Color(242, 98, 15));
        btnBuscar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Seleccionar");
        btnBuscar.setBorder(null);
        bg.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 120, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoMembresiaActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMembresiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMembresiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMembresiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMembresiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMembresiaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCobrar;
    public javax.swing.JComboBox<String> cmbCriterioBusqueda;
    public javax.swing.JComboBox<String> cmbTipoMembresia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jtMembresia;
    public javax.swing.JLabel lblDescripcionMembresia;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtBusqueda;
    public javax.swing.JTextField txtCambio;
    public javax.swing.JTextField txtCedula1;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtEfectivo;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtIVA;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtSubtotal;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
